const SHEET_ID='1bcKCFnjmBDh6R2d3tpc7EKQ_ZVCYs8HnvyptOTx65Dw';
const SHEETS={nasional:'Nasional',faskes:'Faskes',target:'TARGET_KEC'};
const demo={nasional:[['PROVINSI','TARGET PB','TARGET PB KBPP','TARGET PB MKJP','PB_TOTAL','PB KBPP','PB MKJP'],['BALI',29821,5387,6844,48,39,26],['JAWA BARAT',131676,44757,25869,2527,1269,579],['JAWA TENGAH',194483,38778,96452,4978,2488,1090]],faskes:[['tanggal','Provinsi','Kabupaten','Kecamatan','Kelurahan','PB TOTAL','PB MKJP','PB KBPP'],['8-9-2026','BALI','BADUNG','MENGWI','MENGWI',88,83,80],['8-9-2026','BALI','BADUNG','KUTA SELATAN','BENOA',82,78,75],['8-9-2026','BALI','GIANYAR','UBUD','PELIATAN',91,88,85],['8-9-2026','BALI','KOTA DENPASAR','DENPASAR SELATAN','PANJER',94,90,87]],target:[['Kabupaten','Kecamatan','Target'],['BADUNG','MENGWI',150],['BADUNG','KUTA SELATAN',120],['GIANYAR','UBUD',160],['KOTA DENPASAR','DENPASAR SELATAN',190]]};
let state={data:demo,indicator:'PB TOTAL',date:'ALL',province:'ALL',district:'ALL',subdistrict:'ALL'};
const $=id=>document.getElementById(id), normalize=v=>String(v??'').trim().toUpperCase().replace(/[_.-]+/g,' ').replace(/\s+/g,' ');
const number=v=>{const s=String(v??'').replace(/[^0-9.,-]/g,'');const n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s.replace(/(\d)\.(\d{3})(?!\d)/g,'$1$2'));return Number.isFinite(n)?n:0};
function parseCsv(t){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function objects(rows){if(!rows?.length)return[];const h=rows[0].map(normalize);return rows.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])))}
function field(o,names){const k=Object.keys(o).find(x=>names.map(normalize).includes(normalize(x)));return k?o[k]:''}
function metric(o){const names={'PB TOTAL':['PB TOTAL','PB_TOTAL'],KBPP:['KBPP','PB KBPP'],MKJP:['MKJP','PB MKJP']}[state.indicator]||[state.indicator];return number(field(o,names))}
function allFaskes(){return objects(state.data.faskes)}
function unique(rows,names){return[...new Set(rows.map(o=>field(o,names)).filter(Boolean))].sort()}
function options(id,values,current,label){$(id).innerHTML=`<option value="ALL">${label}</option>`+values.map(v=>`<option value="${v}" ${normalize(v)===normalize(current)?'selected':''}>${v}</option>`).join('')}
function dateOf(o){return normalize(field(o,['TANGGAL','DATE','PERIODE']))}
function campaignDates(){const dates=[];for(let day=7;day<=30;day++)dates.push(`${day}-9-2026`);for(let day=1;day<=10;day++)dates.push(`${day}-10-2026`);return dates}
function filterRows(){return allFaskes().filter(o=>(state.date==='ALL'||dateOf(o)===normalize(state.date))&&(state.province==='ALL'||!field(o,['PROVINSI','PROVINCE'])||normalize(field(o,['PROVINSI','PROVINCE']))===normalize(state.province))&&(state.district==='ALL'||normalize(field(o,['KABUPATEN','KABUPATEN KOTA','KAB KOTA']))===normalize(state.district))&&(state.subdistrict==='ALL'||normalize(field(o,['KECAMATAN','NAMA KECAMATAN']))===normalize(state.subdistrict)))}
function renderFilters(){const rows=allFaskes();const nationalProvinces=unique(objects(state.data.nasional),['PROVINSI']);const provinces=unique(rows,['PROVINSI','PROVINCE']).length?unique(rows,['PROVINSI','PROVINCE']):nationalProvinces;options('dateSelect',campaignDates(),state.date,'Semua tanggal');options('provinceSelect',provinces,state.province,'Semua Provinsi');const pRows=rows.filter(o=>state.province==='ALL'||!field(o,['PROVINSI','PROVINCE'])||normalize(field(o,['PROVINSI','PROVINCE']))===normalize(state.province));options('districtSelect',unique(pRows,['KABUPATEN','KABUPATEN KOTA','KAB KOTA']),state.district,'Semua Kabupaten / Kota');const dRows=pRows.filter(o=>state.district==='ALL'||normalize(field(o,['KABUPATEN','KABUPATEN KOTA','KAB KOTA']))===normalize(state.district));options('subdistrictSelect',unique(dRows,['KECAMATAN','NAMA KECAMATAN']),state.subdistrict,'Semua Kecamatan')}
function formatNumber(v){return Math.round(v).toLocaleString('id-ID')}
function nationalPerformance(o){const aliases={'PB TOTAL':['TARGET PB'],KBPP:['TARGET PB KBPP'],MKJP:['TARGET PB MKJP']}[state.indicator];const target=number(field(o,aliases||[]));return target?metric(o)/target*100:0}
function renderNational(){const rows=objects(state.data.nasional).filter(o=>normalize(field(o,['PROVINSI']))!=='NASIONAL').map(o=>({name:field(o,['PROVINSI']),value:nationalPerformance(o)})).sort((a,b)=>b.value-a.value);const max=Math.max(1,...rows.map(x=>x.value));$('nationalScale').innerHTML='';$('nationalChart').innerHTML=rows.map(x=>{const bali=normalize(x.name)==='BALI';const value=x.value.toLocaleString('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2});return `<div class="national-row"><span class="national-name ${bali?'bali-text':''}" title="${x.name}">${x.name}</span><div class="national-track"><i class="${bali?'bali':'actual'}" style="width:${x.value/max*100}%"></i></div><b class="national-value ${bali?'bali-text':''}">${value}%</b></div>`}).join('')}
function group(rows,names){const map={};rows.forEach(o=>{const n=field(o,names)||'Belum diisi';(map[n]??=[]).push(o)});return Object.entries(map).map(([name,items])=>({name,value:items.reduce((s,o)=>s+metric(o),0),rows:items}))}
function targetFor(name,district){const found=objects(state.data.target).find(o=>{const sameName=normalize(field(o,['KECAMATAN','NAMA KECAMATAN']))===normalize(name);const sameDistrict=!district||normalize(field(o,['KABUPATEN','KABUPATEN KOTA']))===normalize(district);return sameName&&sameDistrict});return found?number(field(found,['TARGET','TARGET KEC','TARGET KECAMATAN'])):0}
function percentRanks(rows){return group(rows,['KECAMATAN','NAMA KECAMATAN']).map(x=>{const district=field(x.rows[0],['KABUPATEN','KABUPATEN KOTA']);const target=targetFor(x.name,district);return{...x,target,score:target?x.value/target*100:null}}).sort((a,b)=>(b.score??-1)-(a.score??-1))}
function ranking(items){return items.map((x,i)=>`<div class="rank-row"><span class="rank-number">${String(i+1).padStart(2,'0')}</span><div><span class="rank-name">${x.name}</span><div class="rank-bar"><i style="width:${Math.min(x.score??0,100)}%"></i></div></div><span class="rank-score">${x.score===null?'N/A':Math.round(x.score)+'%'}</span></div>`).join('')||'<div class="muted">Belum ada data.</div>'}
function horizontal(items){const max=Math.max(1,...items.map(x=>x.score??x.value));return items.map(x=>`<div class="hbar-row"><span>${x.name}</span><div><i style="width:${(x.score??x.value)/max*100}%"></i></div><b>${x.score===null?formatNumber(x.value):Math.round(x.score)+'%'}</b></div>`).join('')||'<div class="muted">Pilih wilayah untuk melihat grafik.</div>'}
function renderRegional(){const rows=filterRows(),hasProvince=state.province!=='ALL',hasDistrict=state.district!=='ALL';if(!hasProvince){$('regionalTitle').textContent='Pilih provinsi untuk melihat kabupaten';$('regionalChartTitle').textContent='Capaian kabupaten / kota';$('regionalChartNote').textContent='Grafik batang horizontal muncul setelah provinsi dipilih';$('regionalChart').innerHTML='';$('highRanking').innerHTML='';$('lowRanking').innerHTML='';return}if(!hasDistrict){const items=group(rows,['KABUPATEN','KABUPATEN KOTA','KAB KOTA']).sort((a,b)=>b.value-a.value);$('regionalTitle').textContent=`Provinsi ${state.province}`;$('regionalChartTitle').textContent='Capaian kabupaten / kota';$('regionalChartNote').textContent='Grafik batang horizontal · absolut indikator terpilih';$('regionalChart').innerHTML=horizontal(items);const ranks=percentRanks(rows);$('highRanking').innerHTML=ranking(ranks.slice(0,10));$('lowRanking').innerHTML=ranking([...ranks].reverse().slice(0,10));return}const items=group(rows,['KECAMATAN','NAMA KECAMATAN']).sort((a,b)=>b.value-a.value);$('regionalTitle').textContent=`${state.province} · ${state.district}`;$('regionalChartTitle').textContent='Capaian per kecamatan';$('regionalChartNote').textContent='Grafik batang horizontal · absolut indikator terpilih';$('regionalChart').innerHTML=horizontal(items);const villages=group(rows,['KELURAHAN','DESA','DESA KELURAHAN']).sort((a,b)=>b.value-a.value);$('highRanking').innerHTML=ranking(villages.slice(0,5).map(x=>({...x,score:x.value})));$('lowRanking').innerHTML=ranking(villages.slice(-5).reverse().map(x=>({...x,score:x.value})));$('highTitle').textContent='5 desa tertinggi';$('lowTitle').textContent='5 desa terendah'}
function renderTable(){const rows=filterRows();$('villageCount').textContent=`${rows.length} baris`;$('villageTable').innerHTML=rows.slice(0,300).map(o=>`<tr><td>${field(o,['PROVINSI','PROVINCE'])||'-'}</td><td>${field(o,['KABUPATEN','KABUPATEN KOTA','KAB KOTA'])||'-'}</td><td>${field(o,['KECAMATAN','NAMA KECAMATAN'])||'-'}</td><td>${field(o,['KELURAHAN','DESA','DESA KELURAHAN'])||'-'}</td><td><b>${formatNumber(metric(o))}</b></td><td>${state.district==='ALL'?'Faskes':'Realisasi'}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada data.</td></tr>'}
function renderKpis(){const rows=filterRows(),total=rows.reduce((s,o)=>s+metric(o),0);$('kpiGrid').innerHTML=`<div class="kpi accent"><div class="kpi-label"><span>${state.indicator}</span><span>01</span></div><div class="kpi-value">${formatNumber(total)}</div><div class="kpi-foot">realisasi sesuai pilihan</div></div><div class="kpi"><div class="kpi-label"><span>Wilayah aktif</span><span>02</span></div><div class="kpi-value">${unique(rows,['KABUPATEN','KABUPATEN KOTA']).length}</div><div class="kpi-foot">kabupaten / kota</div></div><div class="kpi"><div class="kpi-label"><span>Kecamatan aktif</span><span>03</span></div><div class="kpi-value">${unique(rows,['KECAMATAN']).length}</div><div class="kpi-foot">berdasarkan Faskes</div></div><div class="kpi"><div class="kpi-label"><span>Desa aktif</span><span>04</span></div><div class="kpi-value">${unique(rows,['KELURAHAN','DESA']).length}</div><div class="kpi-foot">tanpa target desa</div></div>`;$('ringValue').textContent=formatNumber(total);$('ringChart').style.background='conic-gradient(var(--orange) 72deg,#edf0eb 0deg)';$('totalServices').textContent=formatNumber(total);$('activeRegions').textContent=unique(rows,['PROVINSI']).length;$('remainingDays').textContent='34'}
function render(){renderFilters();renderKpis();renderNational();renderRegional();renderTable()}
async function loadData(){ $('syncStatus').textContent='Menyinkronkan data...';try{const data={};for(const key of Object.keys(SHEETS)){const response=await fetch(`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(SHEETS[key])}`,{cache:'no-store'});if(!response.ok)throw Error();data[key]=parseCsv(await response.text())}state.data=data;$('syncStatus').textContent='Data terhubung · diperbarui hari ini'}catch(error){state.data=demo;$('syncStatus').textContent='Mode demo · buka akses CSV untuk sinkronisasi'}render()}
const map={dateSelect:'date',provinceSelect:'province',districtSelect:'district',subdistrictSelect:'subdistrict'};for(const id of Object.keys(map))$(id).addEventListener('change',e=>{state[map[id]]=e.target.value;if(id==='provinceSelect'){state.district='ALL';state.subdistrict='ALL'}if(id==='districtSelect')state.subdistrict='ALL';render()});$('indicatorSelect').addEventListener('change',e=>{state.indicator=e.target.value;render()});$('refreshButton').addEventListener('click',loadData);$('downloadButton').addEventListener('click',()=>{const csv=[['Provinsi','Kabupaten','Kecamatan','Desa','Capaian'],...filterRows().map(o=>[field(o,['PROVINSI']),field(o,['KABUPATEN']),field(o,['KECAMATAN']),field(o,['KELURAHAN','DESA']),metric(o)])].map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='monitoring-wcd.csv';a.click()});render();loadData();
